Exercicio 1 

In [2]:
import numpy as np

array1 = np.ones(8, dtype=int)
array2 = np.random.randint(0, 10, 8)
array3 = array1 + array2

if np.sum(array3) >= 40:
    array3 = array3.reshape(4, 2)  
else:
    array3 = array3.reshape(2, 4)  

print("Matriz resultante:\n", array3)


Matriz resultante:
 [[ 6 10]
 [ 1  2]
 [ 1  6]
 [ 5  9]]


Exercicio 2 

In [5]:
pares1 = np.arange(0, 52, 2)  
pares2 = np.arange(100, 48, -2)  

concatenado = np.concatenate((pares1, pares2))
ordenado = np.sort(concatenado)

print(" Array ordenado:", ordenado)

 Array ordenado: [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Exercicio 3

In [ ]:
campo = np.zeros((2, 2), dtype=int)
pos_x, pos_y = np.random.randint(0, 2), np.random.randint(0, 2)
campo[pos_x, pos_y] = 1

tentativas = 3
for i in range(tentativas):
    print("Mini Campo Minado")
    x = int(input("Escolha a linha (0 ou 1): "))
    y = int(input("Escolha a coluna (0 ou 1): "))

    if campo[x, y] == 1:
        print("Game Over! :( Try Again!")
        break
    elif i == tentativas - 1:
        print("Congratulations! You beat the game! :)")

Exercicio 4

In [ ]:
matriz = np.random.randint(0, 10, (3, 4))
print("Matriz:")
print(matriz)

# Extraindo número de linhas e colunas
linhas, colunas = matriz.shape

# Multiplicando número de linhas e colunas
num_elementos = linhas * colunas

# Verificando se pode se tornar um vetor com número par ou ímpar de elementos
if num_elementos % 2 == 0:
    print(f"A matriz pode se tornar um vetor unidimensional com {num_elementos} elementos (PAR).") #f para mostrar o valor de num_elementoss 
else:
    print(f"A matriz pode se tornar um vetor unidimensional com {num_elementos} elementos (ÍMPAR).")


Matriz:
[[2 3 2 5]
 [7 1 4 6]
 [0 2 9 4]]
A matriz pode se tornar um vetor unidimensional com 12 elementos (PAR).


Exercicio 5

In [25]:
np.random.seed(0)

# Criando a matriz 4x4 
matriz = np.random.randint(1, 50, (4, 4))
print("Matriz gerada:")
print(matriz)

# a) Calcular a média de cada linha e coluna
media_colunas = np.mean(matriz,axis=1)
media_linhas = np.mean(matriz,axis=1)
print("\nMédia de cada linha:", media_linhas)
print("Média de cada coluna:", media_colunas)

# b) Maior valor entre as médias das linhas e colunas
maior_media_linhas = np.max(media_linhas)
maior_media_colunas = np.max(media_colunas)
print("Maior média das linhas:", maior_media_linhas)
print("Maior média das colunas:", maior_media_colunas)

# c) Contagem das ocorrências dos números na matriz

valores, contagens = np.unique(matriz, return_counts=True)
contagem_numeros = dict(zip(valores, contagens))

print("\nFrequência de cada número na matriz:")
for num, qtd in contagem_numeros.items():
    print(f"Número {num} = {qtd} vezes")
# Filtrar os números que aparecem exatamente 2 vezes
print("\nNúmeros que aparecem exatamente 2 vezes:")
for num, qtd in contagem_numeros.items():
    if qtd == 2:
        print(f"Número {num} ")

Matriz gerada:
[[45 48  1  4]
 [ 4 40 10 20]
 [22 37 24  7]
 [25 25 13  2]]

Média de cada linha: [24.5  18.5  22.5  16.25]
Média de cada coluna: [24.5  18.5  22.5  16.25]
Maior média das linhas: 24.5
Maior média das colunas: 24.5

Frequência de cada número na matriz:
Número 1 = 1 vezes
Número 2 = 1 vezes
Número 4 = 2 vezes
Número 7 = 1 vezes
Número 10 = 1 vezes
Número 13 = 1 vezes
Número 20 = 1 vezes
Número 22 = 1 vezes
Número 24 = 1 vezes
Número 25 = 2 vezes
Número 37 = 1 vezes
Número 40 = 1 vezes
Número 45 = 1 vezes
Número 48 = 1 vezes

Números que aparecem exatamente 2 vezes:
Número 4 
Número 25 
